package com.engineering.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.math.BigDecimal;
import java.sql.Date;

@DynamoDBTable(tableName = "Employee")
public class Employee {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private long employeeId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private Date dateOfJoining;

    @DynamoDBAttribute
    private BigDecimal salary;

    @DynamoDBAttribute
    private BigDecimal gemsAwarded;

    public long getEmployeeId() {
        return employeeId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getDateOfJoining() {
        return dateOfJoining;
    }

    public void setDateOfJoining(Date dateOfJoining) {
        this.dateOfJoining = dateOfJoining;
    }

    public BigDecimal getSalary() {
        return salary;
    }

    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    public BigDecimal getGemsAwarded() {
        return gemsAwarded;
    }

    public void setGemsAwarded(BigDecimal gemsAwarded) {
        this.gemsAwarded = gemsAwarded;
    }


}
